name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

# 工作流配置
permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

# 全局环境变量
env:
  PYTHON_VERSIONS: "3.9,3.10,3.11,3.12"
  BUILD_CACHE_VERSION: "v1"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_SECURE_MODE: "true"